[theme]
name = "solarized-dark"
[theme.overrides]
idle_bg = "#2E3440"
idle_fg = "#E5E9F0"
info_bg = "#D08770"
info_fg = "#2E3440"
good_bg = "#BF616A"
good_fg = "#2E3440"
warning_bg = "#5E81AC"
warning_fg = "#2E3440"
critical_bg = "#88C0D0"
critical_fg = "#2E3440"
separator = ""

[icons]
name = "awesome"

# [[block]]
# block = "cpu"
# interval = 10

# [[block]]
# block = "memory"
# format_mem = "{Mup}%"
# display_type = "memory"
# icons = true
# clickable = false
# interval = 5
# warning_mem = 80
# critical_mem = 95

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
